proswap/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ShareController;
use App\Http\Controllers\SCPIController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', [DashboardController::class, "index"])->name('dashboard');

    Route::get('/product', [ProductController::class, "index"])->name('product');
    Route::get('/SCPI', [SCPIController::class, "index"])->name('scpi');
    Route::get('/share-wait', [ShareController::class, "show_wait"])->name('share-wait');
    Route::get('/showConfirmPurchase', [ShareController::class, "showConfirmPurchase"])->name('showConfirmPurchase');
    Route::get('/history', [ShareController::class, "history"])->name('history');

    Route::get('/products/{id}', [ShareController::class, 'getProduct'])->name('get-product');
    Route::get('/getScpiName/{id}', [ShareController::class, 'getScpiName'])->name('get-ScpiName');
    
    Route::post('/add-scpi', [SCPIController::class, "add"])->name('add-scpi');
    Route::post('/add-product', [ProductController::class, "add"])->name('add-product');

    Route::get('/buy-share/{share_id}', [ShareController::class, "index"])->name('buy-share');
    Route::post('/confirm-buy-share/{id}', [ShareController::class, "buy"])->name('confirm-buy-share');
    Route::post('/confirm-sold-share', [ShareController::class, "sold"])->name('confirm-sold-share');
    Route::post('/buyConfirmForm/{id}', [ShareController::class, "buyConfirmForm"])->name('buyConfirmForm');
    Route::get('/confirmPurchase/{id}', [ShareController::class, "confirmPurchase"])->name('confirmPurchase');
    Route::get('/refusePurchase/{id}', [ShareController::class, "refusePurchase"])->name('refusePurchase');
});

proswap/app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

proswap/app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

proswap/resources/views/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ env('APP_NAME') }} Dashboard</title>

    <!--  style  -->
    @vite([
        'resources/scss/dashboard.scss',
            
    
    //  <!-- Scripts -->
        'resources/js/dashboard.js'
    ])
</head>
<body>
    <x-app-layout>
        
        <div class="projects-section">
            <div class="projects-section-header">
              <p>Dashboard</p>
              <p class="time">{{ \Carbon\Carbon::now()->locale('fr_FR')->isoFormat('dddd D MMMM YYYY') }}</p>
            </div>
            <div class="projects-section-line">
                <div class="projects-status">
                    <div class="item-status">
                    <span class="status-number">{{ $user->parts_total }}</span>
                    <span class="status-type">Parts détenues</span>
                </div>
                <div class="item-status">
                    <span class="status-number">{{ $user->parts_buy }}</span>
                    <span class="status-type">Parts acheter</span>
                </div>
                <div class="item-status">
                    <span class="status-number">{{ $user->parts_sold }}</span>
                    <span class="status-type">Parts vendu</span>
                </div>
            </div>
            <div class="view-actions">
                <button class="view-btn list-view" title="List View">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-list">
                    <line x1="8" y1="6" x2="21" y2="6" />
                    <line x1="8" y1="12" x2="21" y2="12" />
                    <line x1="8" y1="18" x2="21" y2="18" />
                    <line x1="3" y1="6" x2="3.01" y2="6" />
                    <line x1="3" y1="12" x2="3.01" y2="12" />
                    <line x1="3" y1="18" x2="3.01" y2="18" /></svg>
                </button>
                <button class="view-btn grid-view active" title="Grid View">
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-grid">
                    <rect x="3" y="3" width="7" height="7" />
                    <rect x="14" y="3" width="7" height="7" />
                    <rect x="14" y="14" width="7" height="7" />
                    <rect x="3" y="14" width="7" height="7" /></svg>
                </button>
              </div>
            </div>
            <div class="project-boxes jsGridView">
                @foreach ($shares as $share)
                    <div class="project-box-wrapper">
                        <div class="project-box" style="background-color: #d5deff;">
                        <div class="project-box-content-header">
                            <p class="box-content-header">{{ $share['share'] }}</p>
                            <p class="box-content-subheader">{{ $share['scpi'] }}</p>
                        </div>
                        <div class="box-progress-wrapper">
                            <p class="box-progress-header">Progress</p>
                            <div class="box-progress-bar">
                            <span class="box-progress" style="width: {{ $share['percentage'] }}%; background-color: #4067f9"></span>
                            </div>
                            <p class="box-progress-percentage">{{ $share['percentage'] }}%</p>
                        </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="messages-section">
            <button class="messages-close">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x-circle">
                <circle cx="12" cy="12" r="10" />
                <line x1="15" y1="9" x2="9" y2="15" />
                <line x1="9" y1="9" x2="15" y2="15" /></svg>
            </button>
            <div class="projects-section-header">
            <p>Nombre d'annonces en portefeuille</p>
            </div>
            <div class="messages">
                @foreach ($shares as $share)
                    <div class="message-box">
                        <img src="{{ $share['photo'] }}" alt="profile image">
                        <div class="message-content">
                            <div class="message-header">
                                <div class="name"><span>Nom : {{ $share['share'] }}</span></div>
                                <br>
                            </div>
                            <br>
                            <p>
                            <span>Mes parts : {{ $share['total_parts'] }}</span>  
                            </p>
                            <br>
                            <p>
                                <span>Dernier achat : {{ $share['last_buy'] }}</span>
                            </p>
                        </div>
                    </div>
                @endforeach
            </div>        

    </x-app-layout>
</body>
</html>

proswap/resources/views/navigation-menu.blade.php
<div class="app-sidebar">
    <a href="{{ route('dashboard') }}" class="app-sidebar-link active">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
        <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
        <polyline points="9 22 9 12 15 12 15 22" /></svg>
    </a>
    <a href="{{ route('scpi') }}" class="app-sidebar-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-bag">
            <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
            <circle cx="9" cy="7" r="4"></circle>
            <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
            <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
        </svg>
    </a>
    <a href="{{ route('product') }}" class="app-sidebar-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-bag"><path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"></path><line x1="3" y1="6" x2="21" y2="6"></line><path d="M16 10a4 4 0 0 1-8 0"></path></svg>
    </a> 
    <a href="{{ route('share-wait') }}" class="app-sidebar-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
    </a>
    <a href="{{ route('history') }}" class="app-sidebar-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2">
            <line x1="18" y1="20" x2="18" y2="10"></line>
            <line x1="12" y1="20" x2="12" y2="4"></line>
            <line x1="6" y1="20" x2="6" y2="14"></line>
        </svg>
    </a>    
    <a href="{{ route('showConfirmPurchase') }}" class="app-sidebar-link">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-circle">
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
            <polyline points="22 4 12 14.01 9 11.01"></polyline>
        </svg>
    </a>
    <a href="{{ route('profile.show') }}" class="app-sidebar-link">
    <svg class="link-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="feather feather-settings" viewBox="0 0 24 24">
        <defs />
        <circle cx="12" cy="12" r="3" />
        <path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-2 2 2 2 0 01-2-2v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83 0 2 2 0 010-2.83l.06-.06a1.65 1.65 0 00.33-1.82 1.65 1.65 0 00-1.51-1H3a2 2 0 01-2-2 2 2 0 012-2h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 010-2.83 2 2 0 012.83 0l.06.06a1.65 1.65 0 001.82.33H9a1.65 1.65 0 001-1.51V3a2 2 0 012-2 2 2 0 012 2v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 0 2 2 0 010 2.83l-.06.06a1.65 1.65 0 00-.33 1.82V9a1.65 1.65 0 001.51 1H21a2 2 0 012 2 2 2 0 01-2 2h-.09a1.65 1.65 0 00-1.51 1z" />
    </svg>
    </a>
    <form method="POST" action="{{ route('logout') }}" x-data>
        @csrf
            <a href="{{ route('logout') }}" onclick="event.preventDefault();
            this.closest('form').submit(); " role="button" class="app-sidebar-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path><polyline points="16 17 21 12 16 7"></polyline><line x1="21" y1="12" x2="9" y2="12"></line></svg>
            </a>   
    </form>
    <button class="mode-switch app-sidebar-link" title="Switch Theme">
        <svg class="moon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" width="24" height="24" viewBox="0 0 24 24">
            <defs></defs>
            <path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"></path>
        </svg>
    </button> 
</div>

proswap/resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                <h1>Politique de sécurité</h1>
                <p>
                    1.	Identification et authentification
                    Les utilisateurs doivent s'identifier en utilisant une adresse e-mail et un mot de passe fort.
                    Les mots de passe doivent être stockés de manière sécurisée en utilisant un hachage fort et un sel unique pour chaque utilisateur.
                    Les utilisateurs doivent être encouragés à utiliser une authentification à deux facteurs pour renforcer leur sécurité.
                </p>
                <p>
                    2.	Gestion des accès
                    Les utilisateurs doivent avoir des niveaux d'accès appropriés en fonction de leur rôle et de leurs responsabilités.
                    Les droits d'accès doivent être revus régulièrement pour s'assurer qu'ils sont toujours appropriés et mis à jour en conséquence.
                    Les anciens comptes d'utilisateurs doivent être désactivés immédiatement lorsqu'un utilisateur quitte l'entreprise ou n'a plus besoin d'accéder au système.
                </p>
                <p>
                    3.	Gestion des vulnérabilités
                    Les mises à jour de sécurité pour le système d'exploitation, les logiciels et les applications doivent être appliquées régulièrement pour prévenir les vulnérabilités.
                    Les vulnérabilités connues doivent être suivies et corrigées dès que possible.
                    Les tests de pénétration doivent être effectués régulièrement pour identifier les vulnérabilités et les corriger avant qu'elles ne soient exploitées.
                </p>
                <p>
                    4.	Surveillance et gestion des incidents
                    Les activités du système et les logs doivent être surveillés régulièrement pour détecter les activités suspectes ou malveillantes.
                    Les incidents de sécurité doivent être signalés immédiatement à l'administrateur système pour une réponse rapide.
                    Les plans d'intervention en cas d'incident doivent être en place et régulièrement mis à jour pour s'assurer qu'ils sont efficaces.
                </p>
                <p>
                    5.	Sécurité physique
                    Le serveur doit être hébergé dans un centre de données sécurisé avec des mesures de sécurité physiques appropriées.
                    Les sauvegardes doivent être stockées dans un emplacement sûr et hors site pour assurer la récupération des données en cas de perte ou de catastrophe.
                </p>
                <p>
                    6.	Politique de confidentialité
                    Les données des utilisateurs doivent être collectées et stockées conformément à la politique de confidentialité.
                    Les utilisateurs doivent être informés de la façon dont leurs données seront utilisées et protégées.
                    Les politiques de confidentialité doivent être régulièrement révisées pour s'assurer qu'elles sont toujours conformes aux réglementations applicables.
                </p>
            </div>
        </div>
    </div>
</x-guest-layout>

proswap/resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                <h1>Condition d'utilisation</h1>
                <p>
                    1.	Acceptation des conditions d'utilisation
                    En utilisant le site web ProSwap, vous acceptez les présentes conditions d'utilisation et vous vous engagez à les respecter. Si vous n'êtes pas d'accord avec ces conditions, veuillez ne pas utiliser ce site.
                </p>
                <p>
                    2.	 Accès au site
                    Le site est accessible gratuitement depuis n’importe où par tout utilisateur disposant d’un accès à Internet. Tous les frais nécessaires pour l’accès aux services (matériel informatique, connexion Internet…) sont à la charge de l’utilisateur.
                    L’accès aux services dédiés aux membres s’effectue à l’aide d’un identifiant et d’un mot de passe.
                    Pour des raisons de maintenance ou autres, l’accès au site peut être interrompu ou suspendu par l’éditeur sans préavis ni justification.
                </p>
                <p>
                    3.	Propriété intellectuelle
                    Tous les contenus, tels que les textes, les images et les vidéos, présents sur le site web ProSwap sont la propriété exclusive de ProSwap ou de ses partenaires et sont protégés par les lois sur les droits d'auteur. Vous ne pouvez pas utiliser, copier ou distribuer ces contenus sans l'autorisation préalable de ProSwap.
                </p>
                <p>
                    4.	Confidentialité
                    ProSwap respecte la vie privée de ses utilisateurs et collecte et utilise les données personnelles conformément à sa politique de confidentialité. En utilisant le site web ProSwap, vous acceptez la collecte et l'utilisation de vos données personnelles conformément à cette politique.
                </p>
                <p>
                    5.	 Cookies
                    Lors des visites sur le site, l’installation automatique d’un cookie sur le logiciel de navigation de l’Utilisateur peut survenir.
                    Les cookies correspondent à de petits fichiers déposés temporairement sur le disque dur de l’ordinateur de l’Utilisateur. Ces cookies sont nécessaires pour assurer l’accessibilité et la navigation sur le site. Ces fichiers ne comportent pas d’informations personnelles et ne peuvent pas être utilisés pour l’identification d’une personne.
                    L’information présente dans les cookies est utilisée pour améliorer les performances de navigation sur le site ProSwap.
                    En naviguant sur le site, l’Utilisateur accepte les cookies. Leur désactivation peut s’effectuer via les paramètres du logiciel de navigation.
                </p>
                <p>
                    6.	Droit applicable et juridiction compétente
                    Le présent contrat est soumis à la législation française. L’absence de résolution à l’amiable des cas de litige entre les parties implique le recours aux tribunaux français compétents pour régler le contentieux.
                </p>
                <p>
                    7.	Modifications des conditions d'utilisation
                    ProSwap se réserve le droit de modifier les présentes conditions d'utilisation à tout moment et sans préavis. Nous vous invitons à consulter régulièrement cette page pour être informé des éventuelles modifications.
                </p>

                <p>
                    En utilisant le site web ProSwap, vous acceptez toutes les conditions d'utilisation présentées ci-dessus. Si vous avez des questions ou des préoccupations concernant ces conditions, veuillez nous contacter.
                </p>
            </div>
        </div>
    </div>
</x-guest-layout>